package com.abdulin.nutritionapp.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

enum class AppThemePreset(val displayName: String) {
    NATURE_GREEN("Природа"),
    OCEAN_BLUE("Океан"),
    SUNSET_ORANGE("Закат"),
    OLED_BLACK("AMOLED"),
    LAVENDER("Лаванда"),
    BERRY_PINK("Ягодный"),
    FOREST_DARK("Лес"),
    SAND_EARTH("Песок"),
    MIDNIGHT_NAVY("Ночь"),
    CORAL_HEALTH("Коралл")
}

fun AppThemePreset.toColorScheme(isDark: Boolean): ColorScheme {
    return when (this) {
        AppThemePreset.NATURE_GREEN -> if (isDark) greenDarkScheme() else greenLightScheme()
        AppThemePreset.OCEAN_BLUE -> if (isDark) blueDarkScheme() else blueLightScheme()
        AppThemePreset.SUNSET_ORANGE -> if (isDark) orangeDarkScheme() else orangeLightScheme()
        AppThemePreset.OLED_BLACK -> oledScheme()
        AppThemePreset.LAVENDER -> if (isDark) lavenderDarkScheme() else lavenderLightScheme()
        AppThemePreset.BERRY_PINK -> if (isDark) berryDarkScheme() else berryLightScheme()
        AppThemePreset.FOREST_DARK -> if (isDark) forestDarkScheme() else forestLightScheme()
        AppThemePreset.SAND_EARTH -> if (isDark) sandDarkScheme() else sandLightScheme()
        AppThemePreset.MIDNIGHT_NAVY -> if (isDark) navyDarkScheme() else navyLightScheme()
        AppThemePreset.CORAL_HEALTH -> if (isDark) coralDarkScheme() else coralLightScheme()
    }
}

private fun greenLightScheme() = lightColorScheme(
    primary = GreenPrimary,
    onPrimary = GreenOnPrimary,
    primaryContainer = GreenPrimaryContainer,
    onPrimaryContainer = GreenOnPrimaryContainer,
    secondary = GreenSecondary,
    onSecondary = GreenOnSecondary,
    secondaryContainer = GreenSecondaryContainer,
    onSecondaryContainer = GreenOnSecondaryContainer,
    tertiary = GreenTertiary,
    onTertiary = GreenOnTertiary,
    tertiaryContainer = GreenTertiaryContainer,
    onTertiaryContainer = GreenOnTertiaryContainer,
    background = GreenBackground,
    onBackground = GreenOnBackground,
    surface = GreenSurface,
    onSurface = GreenOnSurface,
    surfaceVariant = GreenSurfaceVariant,
    onSurfaceVariant = GreenOnSurfaceVariant,
    error = GreenError,
    onError = GreenOnError,
    errorContainer = GreenErrorContainer,
    onErrorContainer = GreenOnErrorContainer,
    outline = GreenOutline
)

private fun greenDarkScheme() = darkColorScheme(
    primary = GreenPrimaryDark,
    onPrimary = GreenOnPrimaryDark,
    primaryContainer = GreenPrimaryContainerDark,
    onPrimaryContainer = GreenOnPrimaryContainerDark,
    secondary = GreenSecondaryDark,
    onSecondary = GreenOnSecondaryDark,
    secondaryContainer = GreenSecondaryContainerDark,
    onSecondaryContainer = GreenOnSecondaryContainerDark,
    tertiary = GreenTertiaryDark,
    onTertiary = GreenOnTertiaryDark,
    tertiaryContainer = GreenTertiaryContainerDark,
    onTertiaryContainer = GreenOnTertiaryContainerDark,
    background = GreenBackgroundDark,
    onBackground = GreenOnBackgroundDark,
    surface = GreenSurfaceDark,
    onSurface = GreenOnSurfaceDark,
    surfaceVariant = GreenSurfaceVariantDark,
    onSurfaceVariant = GreenOnSurfaceVariantDark,
    error = GreenErrorDark,
    onError = GreenOnErrorDark,
    errorContainer = GreenErrorContainerDark,
    onErrorContainer = GreenOnErrorContainerDark,
    outline = GreenOutlineDark
)

private fun blueLightScheme() = lightColorScheme(
    primary = BluePrimary,
    onPrimary = BlueOnPrimary,
    primaryContainer = BluePrimaryContainer,
    onPrimaryContainer = BlueOnPrimaryContainer,
    secondary = BlueSecondary,
    onSecondary = BlueOnSecondary,
    secondaryContainer = BlueSecondaryContainer,
    onSecondaryContainer = BlueOnSecondaryContainer,
    tertiary = BlueTertiary,
    onTertiary = BlueOnTertiary,
    tertiaryContainer = BlueTertiaryContainer,
    onTertiaryContainer = BlueOnTertiaryContainer,
    background = BlueBackground,
    onBackground = BlueOnBackground,
    surface = BlueSurface,
    onSurface = BlueOnSurface,
    surfaceVariant = BlueSurfaceVariant,
    onSurfaceVariant = BlueOnSurfaceVariant,
    error = BlueError,
    onError = BlueOnError,
    errorContainer = BlueErrorContainer,
    onErrorContainer = BlueOnErrorContainer,
    outline = BlueOutline
)

private fun blueDarkScheme() = darkColorScheme(
    primary = BluePrimaryDark,
    onPrimary = BlueOnPrimaryDark,
    primaryContainer = BluePrimaryContainerDark,
    onPrimaryContainer = BlueOnPrimaryContainerDark,
    secondary = BlueSecondaryDark,
    onSecondary = BlueOnSecondaryDark,
    secondaryContainer = BlueSecondaryContainerDark,
    onSecondaryContainer = BlueOnSecondaryContainerDark,
    tertiary = BlueTertiaryDark,
    onTertiary = BlueOnTertiaryDark,
    tertiaryContainer = BlueTertiaryContainerDark,
    onTertiaryContainer = BlueOnTertiaryContainerDark,
    background = BlueBackgroundDark,
    onBackground = BlueOnBackgroundDark,
    surface = BlueSurfaceDark,
    onSurface = BlueOnSurfaceDark,
    surfaceVariant = BlueSurfaceVariantDark,
    onSurfaceVariant = BlueOnSurfaceVariantDark,
    error = BlueErrorDark,
    onError = BlueOnErrorDark,
    errorContainer = BlueErrorContainerDark,
    onErrorContainer = BlueOnErrorContainerDark,
    outline = BlueOutlineDark
)

private fun orangeLightScheme() = lightColorScheme(
    primary = OrangePrimary,
    onPrimary = OrangeOnPrimary,
    primaryContainer = OrangePrimaryContainer,
    onPrimaryContainer = OrangeOnPrimaryContainer,
    secondary = OrangeSecondary,
    onSecondary = OrangeOnSecondary,
    secondaryContainer = OrangeSecondaryContainer,
    onSecondaryContainer = OrangeOnSecondaryContainer,
    tertiary = OrangeTertiary,
    onTertiary = OrangeOnTertiary,
    tertiaryContainer = OrangeTertiaryContainer,
    onTertiaryContainer = OrangeOnTertiaryContainer,
    background = OrangeBackground,
    onBackground = OrangeOnBackground,
    surface = OrangeSurface,
    onSurface = OrangeOnSurface,
    surfaceVariant = OrangeSurfaceVariant,
    onSurfaceVariant = OrangeOnSurfaceVariant,
    error = OrangeError,
    onError = OrangeOnError,
    errorContainer = OrangeErrorContainer,
    onErrorContainer = OrangeOnErrorContainer,
    outline = OrangeOutline
)

private fun orangeDarkScheme() = darkColorScheme(
    primary = OrangePrimaryDark,
    onPrimary = OrangeOnPrimaryDark,
    primaryContainer = OrangePrimaryContainerDark,
    onPrimaryContainer = OrangeOnPrimaryContainerDark,
    secondary = OrangeSecondaryDark,
    onSecondary = OrangeOnSecondaryDark,
    secondaryContainer = OrangeSecondaryContainerDark,
    onSecondaryContainer = OrangeOnSecondaryContainerDark,
    tertiary = OrangeTertiaryDark,
    onTertiary = OrangeOnTertiaryDark,
    tertiaryContainer = OrangeTertiaryContainerDark,
    onTertiaryContainer = OrangeOnTertiaryContainerDark,
    background = OrangeBackgroundDark,
    onBackground = OrangeOnBackgroundDark,
    surface = OrangeSurfaceDark,
    onSurface = OrangeOnSurfaceDark,
    surfaceVariant = OrangeSurfaceVariantDark,
    onSurfaceVariant = OrangeOnSurfaceVariantDark,
    error = OrangeErrorDark,
    onError = OrangeOnErrorDark,
    errorContainer = OrangeErrorContainerDark,
    onErrorContainer = OrangeOnErrorContainerDark,
    outline = OrangeOutlineDark
)

private fun oledScheme() = darkColorScheme(
    primary = OledPrimary,
    onPrimary = OledOnPrimary,
    primaryContainer = OledPrimaryContainer,
    onPrimaryContainer = OledOnPrimaryContainer,
    secondary = OledSecondary,
    onSecondary = OledOnSecondary,
    secondaryContainer = OledSecondaryContainer,
    onSecondaryContainer = OledOnSecondaryContainer,
    tertiary = OledTertiary,
    onTertiary = OledOnTertiary,
    tertiaryContainer = OledTertiaryContainer,
    onTertiaryContainer = OledOnTertiaryContainer,
    background = OledBackground,
    onBackground = OledOnBackground,
    surface = OledSurface,
    onSurface = OledOnSurface,
    surfaceVariant = OledSurfaceVariant,
    onSurfaceVariant = OledOnSurfaceVariant,
    error = OledError,
    onError = OledOnError,
    errorContainer = OledErrorContainer,
    onErrorContainer = OledOnErrorContainer,
    outline = OledOutline
)

private fun lavenderLightScheme() = lightColorScheme(
    primary = LavenderPrimary,
    onPrimary = LavenderOnPrimary,
    primaryContainer = LavenderPrimaryContainer,
    onPrimaryContainer = LavenderOnPrimaryContainer,
    secondary = LavenderSecondary,
    onSecondary = LavenderOnSecondary,
    secondaryContainer = LavenderSecondaryContainer,
    onSecondaryContainer = LavenderOnSecondaryContainer,
    tertiary = LavenderTertiary,
    onTertiary = LavenderOnTertiary,
    tertiaryContainer = LavenderTertiaryContainer,
    onTertiaryContainer = LavenderOnTertiaryContainer,
    background = LavenderBackground,
    onBackground = LavenderOnBackground,
    surface = LavenderSurface,
    onSurface = LavenderOnSurface,
    surfaceVariant = LavenderSurfaceVariant,
    onSurfaceVariant = LavenderOnSurfaceVariant,
    error = LavenderError,
    onError = LavenderOnError,
    errorContainer = LavenderErrorContainer,
    onErrorContainer = LavenderOnErrorContainer,
    outline = LavenderOutline
)

private fun lavenderDarkScheme() = darkColorScheme(
    primary = LavenderPrimaryDark,
    onPrimary = LavenderOnPrimaryDark,
    primaryContainer = LavenderPrimaryContainerDark,
    onPrimaryContainer = LavenderOnPrimaryContainerDark,
    secondary = LavenderSecondaryDark,
    onSecondary = LavenderOnSecondaryDark,
    secondaryContainer = LavenderSecondaryContainerDark,
    onSecondaryContainer = LavenderOnSecondaryContainerDark,
    tertiary = LavenderTertiaryDark,
    onTertiary = LavenderOnTertiaryDark,
    tertiaryContainer = LavenderTertiaryContainerDark,
    onTertiaryContainer = LavenderOnTertiaryContainerDark,
    background = LavenderBackgroundDark,
    onBackground = LavenderOnBackgroundDark,
    surface = LavenderSurfaceDark,
    onSurface = LavenderOnSurfaceDark,
    surfaceVariant = LavenderSurfaceVariantDark,
    onSurfaceVariant = LavenderOnSurfaceVariantDark,
    error = LavenderErrorDark,
    onError = LavenderOnErrorDark,
    errorContainer = LavenderErrorContainerDark,
    onErrorContainer = LavenderOnErrorContainerDark,
    outline = LavenderOutlineDark
)

private fun berryLightScheme() = lightColorScheme(
    primary = BerryPrimary,
    onPrimary = BerryOnPrimary,
    primaryContainer = BerryPrimaryContainer,
    onPrimaryContainer = BerryOnPrimaryContainer,
    secondary = BerrySecondary,
    onSecondary = BerryOnSecondary,
    secondaryContainer = BerrySecondaryContainer,
    onSecondaryContainer = BerryOnSecondaryContainer,
    tertiary = BerryTertiary,
    onTertiary = BerryOnTertiary,
    tertiaryContainer = BerryTertiaryContainer,
    onTertiaryContainer = BerryOnTertiaryContainer,
    background = BerryBackground,
    onBackground = BerryOnBackground,
    surface = BerrySurface,
    onSurface = BerryOnSurface,
    surfaceVariant = BerrySurfaceVariant,
    onSurfaceVariant = BerryOnSurfaceVariant,
    error = BerryError,
    onError = BerryOnError,
    errorContainer = BerryErrorContainer,
    onErrorContainer = BerryOnErrorContainer,
    outline = BerryOutline
)

private fun berryDarkScheme() = darkColorScheme(
    primary = BerryPrimaryDark,
    onPrimary = BerryOnPrimaryDark,
    primaryContainer = BerryPrimaryContainerDark,
    onPrimaryContainer = BerryOnPrimaryContainerDark,
    secondary = BerrySecondaryDark,
    onSecondary = BerryOnSecondaryDark,
    secondaryContainer = BerrySecondaryContainerDark,
    onSecondaryContainer = BerryOnSecondaryContainerDark,
    tertiary = BerryTertiaryDark,
    onTertiary = BerryOnTertiaryDark,
    tertiaryContainer = BerryTertiaryContainerDark,
    onTertiaryContainer = BerryOnTertiaryContainerDark,
    background = BerryBackgroundDark,
    onBackground = BerryOnBackgroundDark,
    surface = BerrySurfaceDark,
    onSurface = BerryOnSurfaceDark,
    surfaceVariant = BerrySurfaceVariantDark,
    onSurfaceVariant = BerryOnSurfaceVariantDark,
    error = BerryErrorDark,
    onError = BerryOnErrorDark,
    errorContainer = BerryErrorContainerDark,
    onErrorContainer = BerryOnErrorContainerDark,
    outline = BerryOutlineDark
)

private fun forestLightScheme() = lightColorScheme(
    primary = ForestPrimary,
    onPrimary = ForestOnPrimary,
    primaryContainer = ForestPrimaryContainer,
    onPrimaryContainer = ForestOnPrimaryContainer,
    secondary = ForestSecondary,
    onSecondary = ForestOnSecondary,
    secondaryContainer = ForestSecondaryContainer,
    onSecondaryContainer = ForestOnSecondaryContainer,
    tertiary = ForestTertiary,
    onTertiary = ForestOnTertiary,
    tertiaryContainer = ForestTertiaryContainer,
    onTertiaryContainer = ForestOnTertiaryContainer,
    background = ForestBackground,
    onBackground = ForestOnBackground,
    surface = ForestSurface,
    onSurface = ForestOnSurface,
    surfaceVariant = ForestSurfaceVariant,
    onSurfaceVariant = ForestOnSurfaceVariant,
    error = ForestError,
    onError = ForestOnError,
    errorContainer = ForestErrorContainer,
    onErrorContainer = ForestOnErrorContainer,
    outline = ForestOutline
)

private fun forestDarkScheme() = darkColorScheme(
    primary = ForestPrimaryDark,
    onPrimary = ForestOnPrimaryDark,
    primaryContainer = ForestPrimaryContainerDark,
    onPrimaryContainer = ForestOnPrimaryContainerDark,
    secondary = ForestSecondaryDark,
    onSecondary = ForestOnSecondaryDark,
    secondaryContainer = ForestSecondaryContainerDark,
    onSecondaryContainer = ForestOnSecondaryContainerDark,
    tertiary = ForestTertiaryDark,
    onTertiary = ForestOnTertiaryDark,
    tertiaryContainer = ForestTertiaryContainerDark,
    onTertiaryContainer = ForestOnTertiaryContainerDark,
    background = ForestBackgroundDark,
    onBackground = ForestOnBackgroundDark,
    surface = ForestSurfaceDark,
    onSurface = ForestOnSurfaceDark,
    surfaceVariant = ForestSurfaceVariantDark,
    onSurfaceVariant = ForestOnSurfaceVariantDark,
    error = ForestErrorDark,
    onError = ForestOnErrorDark,
    errorContainer = ForestErrorContainerDark,
    onErrorContainer = ForestOnErrorContainerDark,
    outline = ForestOutlineDark
)

private fun sandLightScheme() = lightColorScheme(
    primary = SandPrimary,
    onPrimary = SandOnPrimary,
    primaryContainer = SandPrimaryContainer,
    onPrimaryContainer = SandOnPrimaryContainer,
    secondary = SandSecondary,
    onSecondary = SandOnSecondary,
    secondaryContainer = SandSecondaryContainer,
    onSecondaryContainer = SandOnSecondaryContainer,
    tertiary = SandTertiary,
    onTertiary = SandOnTertiary,
    tertiaryContainer = SandTertiaryContainer,
    onTertiaryContainer = SandOnTertiaryContainer,
    background = SandBackground,
    onBackground = SandOnBackground,
    surface = SandSurface,
    onSurface = SandOnSurface,
    surfaceVariant = SandSurfaceVariant,
    onSurfaceVariant = SandOnSurfaceVariant,
    error = SandError,
    onError = SandOnError,
    errorContainer = SandErrorContainer,
    onErrorContainer = SandOnErrorContainer,
    outline = SandOutline
)

private fun sandDarkScheme() = darkColorScheme(
    primary = SandPrimaryDark,
    onPrimary = SandOnPrimaryDark,
    primaryContainer = SandPrimaryContainerDark,
    onPrimaryContainer = SandOnPrimaryContainerDark,
    secondary = SandSecondaryDark,
    onSecondary = SandOnSecondaryDark,
    secondaryContainer = SandSecondaryContainerDark,
    onSecondaryContainer = SandOnSecondaryContainerDark,
    tertiary = SandTertiaryDark,
    onTertiary = SandOnTertiaryDark,
    tertiaryContainer = SandTertiaryContainerDark,
    onTertiaryContainer = SandOnTertiaryContainerDark,
    background = SandBackgroundDark,
    onBackground = SandOnBackgroundDark,
    surface = SandSurfaceDark,
    onSurface = SandOnSurfaceDark,
    surfaceVariant = SandSurfaceVariantDark,
    onSurfaceVariant = SandOnSurfaceVariantDark,
    error = SandErrorDark,
    onError = SandOnErrorDark,
    errorContainer = SandErrorContainerDark,
    onErrorContainer = SandOnErrorContainerDark,
    outline = SandOutlineDark
)

private fun navyLightScheme() = lightColorScheme(
    primary = NavyPrimary,
    onPrimary = NavyOnPrimary,
    primaryContainer = NavyPrimaryContainer,
    onPrimaryContainer = NavyOnPrimaryContainer,
    secondary = NavySecondary,
    onSecondary = NavyOnSecondary,
    secondaryContainer = NavySecondaryContainer,
    onSecondaryContainer = NavyOnSecondaryContainer,
    tertiary = NavyTertiary,
    onTertiary = NavyOnTertiary,
    tertiaryContainer = NavyTertiaryContainer,
    onTertiaryContainer = NavyOnTertiaryContainer,
    background = NavyBackground,
    onBackground = NavyOnBackground,
    surface = NavySurface,
    onSurface = NavyOnSurface,
    surfaceVariant = NavySurfaceVariant,
    onSurfaceVariant = NavyOnSurfaceVariant,
    error = NavyError,
    onError = NavyOnError,
    errorContainer = NavyErrorContainer,
    onErrorContainer = NavyOnErrorContainer,
    outline = NavyOutline
)

private fun navyDarkScheme() = darkColorScheme(
    primary = NavyPrimaryDark,
    onPrimary = NavyOnPrimaryDark,
    primaryContainer = NavyPrimaryContainerDark,
    onPrimaryContainer = NavyOnPrimaryContainerDark,
    secondary = NavySecondaryDark,
    onSecondary = NavyOnSecondaryDark,
    secondaryContainer = NavySecondaryContainerDark,
    onSecondaryContainer = NavyOnSecondaryContainerDark,
    tertiary = NavyTertiaryDark,
    onTertiary = NavyOnTertiaryDark,
    tertiaryContainer = NavyTertiaryContainerDark,
    onTertiaryContainer = NavyOnTertiaryContainerDark,
    background = NavyBackgroundDark,
    onBackground = NavyOnBackgroundDark,
    surface = NavySurfaceDark,
    onSurface = NavyOnSurfaceDark,
    surfaceVariant = NavySurfaceVariantDark,
    onSurfaceVariant = NavyOnSurfaceVariantDark,
    error = NavyErrorDark,
    onError = NavyOnErrorDark,
    errorContainer = NavyErrorContainerDark,
    onErrorContainer = NavyOnErrorContainerDark,
    outline = NavyOutlineDark
)

private fun coralLightScheme() = lightColorScheme(
    primary = CoralPrimary,
    onPrimary = CoralOnPrimary,
    primaryContainer = CoralPrimaryContainer,
    onPrimaryContainer = CoralOnPrimaryContainer,
    secondary = CoralSecondary,
    onSecondary = CoralOnSecondary,
    secondaryContainer = CoralSecondaryContainer,
    onSecondaryContainer = CoralOnSecondaryContainer,
    tertiary = CoralTertiary,
    onTertiary = CoralOnTertiary,
    tertiaryContainer = CoralTertiaryContainer,
    onTertiaryContainer = CoralOnTertiaryContainer,
    background = CoralBackground,
    onBackground = CoralOnBackground,
    surface = CoralSurface,
    onSurface = CoralOnSurface,
    surfaceVariant = CoralSurfaceVariant,
    onSurfaceVariant = CoralOnSurfaceVariant,
    error = CoralError,
    onError = CoralOnError,
    errorContainer = CoralErrorContainer,
    onErrorContainer = CoralOnErrorContainer,
    outline = CoralOutline
)

private fun coralDarkScheme() = darkColorScheme(
    primary = CoralPrimaryDark,
    onPrimary = CoralOnPrimaryDark,
    primaryContainer = CoralPrimaryContainerDark,
    onPrimaryContainer = CoralOnPrimaryContainerDark,
    secondary = CoralSecondaryDark,
    onSecondary = CoralOnSecondaryDark,
    secondaryContainer = CoralSecondaryContainerDark,
    onSecondaryContainer = CoralOnSecondaryContainerDark,
    tertiary = CoralTertiaryDark,
    onTertiary = CoralOnTertiaryDark,
    tertiaryContainer = CoralTertiaryContainerDark,
    onTertiaryContainer = CoralOnTertiaryContainerDark,
    background = CoralBackgroundDark,
    onBackground = CoralOnBackgroundDark,
    surface = CoralSurfaceDark,
    onSurface = CoralOnSurfaceDark,
    surfaceVariant = CoralSurfaceVariantDark,
    onSurfaceVariant = CoralOnSurfaceVariantDark,
    error = CoralErrorDark,
    onError = CoralOnErrorDark,
    errorContainer = CoralErrorContainerDark,
    onErrorContainer = CoralOnErrorContainerDark,
    outline = CoralOutlineDark
)
