package com.abdulin.nutritionapp.ui.theme

import androidx.compose.ui.graphics.Color

// ═══════════════════════════════════════════════════════
// 1. Nature Green — свежий зелёный (Material You default)
// ═══════════════════════════════════════════════════════
val GreenPrimary = Color(0xFF00897B)
val GreenOnPrimary = Color(0xFFFFFFFF)
val GreenPrimaryContainer = Color(0xFFB2DFDB)
val GreenOnPrimaryContainer = Color(0xFF00332E)
val GreenSecondary = Color(0xFF4DB6AC)
val GreenOnSecondary = Color(0xFFFFFFFF)
val GreenSecondaryContainer = Color(0xFFCCE8E4)
val GreenOnSecondaryContainer = Color(0xFF00201D)
val GreenTertiary = Color(0xFF80CBC4)
val GreenOnTertiary = Color(0xFFFFFFFF)
val GreenTertiaryContainer = Color(0xFFD4ECEA)
val GreenOnTertiaryContainer = Color(0xFF003533)
val GreenBackground = Color(0xFFF5FBF9)
val GreenOnBackground = Color(0xFF191C1B)
val GreenSurface = Color(0xFFF5FBF9)
val GreenOnSurface = Color(0xFF191C1B)
val GreenSurfaceVariant = Color(0xFFDAE5E2)
val GreenOnSurfaceVariant = Color(0xFF3F4946)
val GreenError = Color(0xFFBA1A1A)
val GreenOnError = Color(0xFFFFFFFF)
val GreenErrorContainer = Color(0xFFFFDAD6)
val GreenOnErrorContainer = Color(0xFF410002)
val GreenOutline = Color(0xFF6F7976)

val GreenPrimaryDark = Color(0xFF80CBC4)
val GreenOnPrimaryDark = Color(0xFF003731)
val GreenPrimaryContainerDark = Color(0xFF005048)
val GreenOnPrimaryContainerDark = Color(0xFFB2DFDB)
val GreenSecondaryDark = Color(0xFFA0D2CB)
val GreenOnSecondaryDark = Color(0xFF0B3731)
val GreenSecondaryContainerDark = Color(0xFF244E47)
val GreenOnSecondaryContainerDark = Color(0xFFCCE8E4)
val GreenTertiaryDark = Color(0xFFA7CFC9)
val GreenOnTertiaryDark = Color(0xFF0B3733)
val GreenTertiaryContainerDark = Color(0xFF254D4A)
val GreenOnTertiaryContainerDark = Color(0xFFD4ECEA)
val GreenBackgroundDark = Color(0xFF191C1B)
val GreenOnBackgroundDark = Color(0xFFE1E3E1)
val GreenSurfaceDark = Color(0xFF191C1B)
val GreenOnSurfaceDark = Color(0xFFE1E3E1)
val GreenSurfaceVariantDark = Color(0xFF3F4946)
val GreenOnSurfaceVariantDark = Color(0xFFBFC9C6)
val GreenErrorDark = Color(0xFFFFB4AB)
val GreenOnErrorDark = Color(0xFF690005)
val GreenErrorContainerDark = Color(0xFF93000A)
val GreenOnErrorContainerDark = Color(0xFFFFDAD6)
val GreenOutlineDark = Color(0xFF899390)

// ═══════════════════════════════════════════════════════
// 2. Ocean Blue — океанский синий (Telegram-inspired)
// ═══════════════════════════════════════════════════════
val BluePrimary = Color(0xFF1976D2)
val BlueOnPrimary = Color(0xFFFFFFFF)
val BluePrimaryContainer = Color(0xFFD1E4FF)
val BlueOnPrimaryContainer = Color(0xFF001D36)
val BlueSecondary = Color(0xFF535F70)
val BlueOnSecondary = Color(0xFFFFFFFF)
val BlueSecondaryContainer = Color(0xFFD7E3F7)
val BlueOnSecondaryContainer = Color(0xFF101C2B)
val BlueTertiary = Color(0xFF6B5778)
val BlueOnTertiary = Color(0xFFFFFFFF)
val BlueTertiaryContainer = Color(0xFFF2DAFF)
val BlueOnTertiaryContainer = Color(0xFF251431)
val BlueBackground = Color(0xFFF8F9FF)
val BlueOnBackground = Color(0xFF191C20)
val BlueSurface = Color(0xFFF8F9FF)
val BlueOnSurface = Color(0xFF191C20)
val BlueSurfaceVariant = Color(0xFFDFE2EB)
val BlueOnSurfaceVariant = Color(0xFF43474E)
val BlueError = Color(0xFFBA1A1A)
val BlueOnError = Color(0xFFFFFFFF)
val BlueErrorContainer = Color(0xFFFFDAD6)
val BlueOnErrorContainer = Color(0xFF410002)
val BlueOutline = Color(0xFF73777F)

val BluePrimaryDark = Color(0xFFA0CAFD)
val BlueOnPrimaryDark = Color(0xFF003258)
val BluePrimaryContainerDark = Color(0xFF00497D)
val BlueOnPrimaryContainerDark = Color(0xFFD1E4FF)
val BlueSecondaryDark = Color(0xFFBBC7DB)
val BlueOnSecondaryDark = Color(0xFF253140)
val BlueSecondaryContainerDark = Color(0xFF3B4858)
val BlueOnSecondaryContainerDark = Color(0xFFD7E3F7)
val BlueTertiaryDark = Color(0xFFD6BEE4)
val BlueOnTertiaryDark = Color(0xFF3B2948)
val BlueTertiaryContainerDark = Color(0xFF523F5F)
val BlueOnTertiaryContainerDark = Color(0xFFF2DAFF)
val BlueBackgroundDark = Color(0xFF111318)
val BlueOnBackgroundDark = Color(0xFFE1E2E8)
val BlueSurfaceDark = Color(0xFF111318)
val BlueOnSurfaceDark = Color(0xFFE1E2E8)
val BlueSurfaceVariantDark = Color(0xFF43474E)
val BlueOnSurfaceVariantDark = Color(0xFFC3C7CF)
val BlueErrorDark = Color(0xFFFFB4AB)
val BlueOnErrorDark = Color(0xFF690005)
val BlueErrorContainerDark = Color(0xFF93000A)
val BlueOnErrorContainerDark = Color(0xFFFFDAD6)
val BlueOutlineDark = Color(0xFF8D9199)

// ═══════════════════════════════════════════════════════
// 3. Sunset Orange — тёплый оранжевый
// ═══════════════════════════════════════════════════════
val OrangePrimary = Color(0xFFF57C00)
val OrangeOnPrimary = Color(0xFFFFFFFF)
val OrangePrimaryContainer = Color(0xFFFFE0B2)
val OrangeOnPrimaryContainer = Color(0xFF3E1F00)
val OrangeSecondary = Color(0xFF77573F)
val OrangeOnSecondary = Color(0xFFFFFFFF)
val OrangeSecondaryContainer = Color(0xFFFFDCC2)
val OrangeOnSecondaryContainer = Color(0xFF2C1600)
val OrangeTertiary = Color(0xFF5A6237)
val OrangeOnTertiary = Color(0xFFFFFFFF)
val OrangeTertiaryContainer = Color(0xFFDEE7B2)
val OrangeOnTertiaryContainer = Color(0xFF181D00)
val OrangeBackground = Color(0xFFFFFBFF)
val OrangeOnBackground = Color(0xFF201A14)
val OrangeSurface = Color(0xFFFFFBFF)
val OrangeOnSurface = Color(0xFF201A14)
val OrangeSurfaceVariant = Color(0xFFF0DFD3)
val OrangeOnSurfaceVariant = Color(0xFF4F453A)
val OrangeError = Color(0xFFBA1A1A)
val OrangeOnError = Color(0xFFFFFFFF)
val OrangeErrorContainer = Color(0xFFFFDAD6)
val OrangeOnErrorContainer = Color(0xFF410002)
val OrangeOutline = Color(0xFF82756A)

val OrangePrimaryDark = Color(0xFFFFB74D)
val OrangeOnPrimaryDark = Color(0xFF522D00)
val OrangePrimaryContainerDark = Color(0xFF744200)
val OrangeOnPrimaryContainerDark = Color(0xFFFFE0B2)
val OrangeSecondaryDark = Color(0xFFE7BEA0)
val OrangeOnSecondaryDark = Color(0xFF442A15)
val OrangeSecondaryContainerDark = Color(0xFF5C402A)
val OrangeOnSecondaryContainerDark = Color(0xFFFFDCC2)
val OrangeTertiaryDark = Color(0xFFC2CB97)
val OrangeOnTertiaryDark = Color(0xFF2D330E)
val OrangeTertiaryContainerDark = Color(0xFF434A20)
val OrangeOnTertiaryContainerDark = Color(0xFFDEE7B2)
val OrangeBackgroundDark = Color(0xFF1A130D)
val OrangeOnBackgroundDark = Color(0xFFEDE0D4)
val OrangeSurfaceDark = Color(0xFF1A130D)
val OrangeOnSurfaceDark = Color(0xFFEDE0D4)
val OrangeSurfaceVariantDark = Color(0xFF4F453A)
val OrangeOnSurfaceVariantDark = Color(0xFFD3C4B6)
val OrangeErrorDark = Color(0xFFFFB4AB)
val OrangeOnErrorDark = Color(0xFF690005)
val OrangeErrorContainerDark = Color(0xFF93000A)
val OrangeOnErrorContainerDark = Color(0xFFFFDAD6)
val OrangeOutlineDark = Color(0xFF9D8E82)

// ═══════════════════════════════════════════════════════
// 4. OLED Black — чистый чёрный
// ═══════════════════════════════════════════════════════
val OledPrimary = Color(0xFFFFFFFF)
val OledOnPrimary = Color(0xFF000000)
val OledPrimaryContainer = Color(0xFF333333)
val OledOnPrimaryContainer = Color(0xFFFFFFFF)
val OledSecondary = Color(0xFFBBBBBB)
val OledOnSecondary = Color(0xFF000000)
val OledSecondaryContainer = Color(0xFF2A2A2A)
val OledOnSecondaryContainer = Color(0xFFE0E0E0)
val OledTertiary = Color(0xFF90CAF9)
val OledOnTertiary = Color(0xFF000000)
val OledTertiaryContainer = Color(0xFF1A1A2E)
val OledOnTertiaryContainer = Color(0xFFBBDEFB)
val OledBackground = Color(0xFF000000)
val OledOnBackground = Color(0xFFE0E0E0)
val OledSurface = Color(0xFF000000)
val OledOnSurface = Color(0xFFE0E0E0)
val OledSurfaceVariant = Color(0xFF1A1A1A)
val OledOnSurfaceVariant = Color(0xFFAAAAAA)
val OledError = Color(0xFFFF6B6B)
val OledOnError = Color(0xFF000000)
val OledErrorContainer = Color(0xFF3D0000)
val OledOnErrorContainer = Color(0xFFFFB4AB)
val OledOutline = Color(0xFF555555)

// ═══════════════════════════════════════════════════════
// 5. Lavender — лаванда (Discord-inspired blurple)
// ═══════════════════════════════════════════════════════
val LavenderPrimary = Color(0xFF7C4DFF)
val LavenderOnPrimary = Color(0xFFFFFFFF)
val LavenderPrimaryContainer = Color(0xFFE8DEFF)
val LavenderOnPrimaryContainer = Color(0xFF22005D)
val LavenderSecondary = Color(0xFF625B71)
val LavenderOnSecondary = Color(0xFFFFFFFF)
val LavenderSecondaryContainer = Color(0xFFE8DEF8)
val LavenderOnSecondaryContainer = Color(0xFF1E192B)
val LavenderTertiary = Color(0xFF7D5260)
val LavenderOnTertiary = Color(0xFFFFFFFF)
val LavenderTertiaryContainer = Color(0xFFFFD8E4)
val LavenderOnTertiaryContainer = Color(0xFF31111D)
val LavenderBackground = Color(0xFFFFFBFF)
val LavenderOnBackground = Color(0xFF1D1B20)
val LavenderSurface = Color(0xFFFFFBFF)
val LavenderOnSurface = Color(0xFF1D1B20)
val LavenderSurfaceVariant = Color(0xFFE7E0EC)
val LavenderOnSurfaceVariant = Color(0xFF49454E)
val LavenderError = Color(0xFFBA1A1A)
val LavenderOnError = Color(0xFFFFFFFF)
val LavenderErrorContainer = Color(0xFFFFDAD6)
val LavenderOnErrorContainer = Color(0xFF410002)
val LavenderOutline = Color(0xFF79747E)

val LavenderPrimaryDark = Color(0xFFCFBCFF)
val LavenderOnPrimaryDark = Color(0xFF381E72)
val LavenderPrimaryContainerDark = Color(0xFF4F378B)
val LavenderOnPrimaryContainerDark = Color(0xFFE8DEFF)
val LavenderSecondaryDark = Color(0xFFCCC2DC)
val LavenderOnSecondaryDark = Color(0xFF332D41)
val LavenderSecondaryContainerDark = Color(0xFF4A4458)
val LavenderOnSecondaryContainerDark = Color(0xFFE8DEF8)
val LavenderTertiaryDark = Color(0xFFEFB8C8)
val LavenderOnTertiaryDark = Color(0xFF4A2532)
val LavenderTertiaryContainerDark = Color(0xFF633B48)
val LavenderOnTertiaryContainerDark = Color(0xFFFFD8E4)
val LavenderBackgroundDark = Color(0xFF141218)
val LavenderOnBackgroundDark = Color(0xFFE6E0E9)
val LavenderSurfaceDark = Color(0xFF141218)
val LavenderOnSurfaceDark = Color(0xFFE6E0E9)
val LavenderSurfaceVariantDark = Color(0xFF49454E)
val LavenderOnSurfaceVariantDark = Color(0xFFCAC4D0)
val LavenderErrorDark = Color(0xFFFFB4AB)
val LavenderOnErrorDark = Color(0xFF690005)
val LavenderErrorContainerDark = Color(0xFF93000A)
val LavenderOnErrorContainerDark = Color(0xFFFFDAD6)
val LavenderOutlineDark = Color(0xFF948F99)

// ═══════════════════════════════════════════════════════
// 6. Berry Pink — яркий розовый (Instagram-inspired)
// ═══════════════════════════════════════════════════════
val BerryPrimary = Color(0xFFE91E63)
val BerryOnPrimary = Color(0xFFFFFFFF)
val BerryPrimaryContainer = Color(0xFFFFD9E2)
val BerryOnPrimaryContainer = Color(0xFF3E0021)
val BerrySecondary = Color(0xFF74565F)
val BerryOnSecondary = Color(0xFFFFFFFF)
val BerrySecondaryContainer = Color(0xFFFFD9E2)
val BerryOnSecondaryContainer = Color(0xFF2B151C)
val BerryTertiary = Color(0xFF7C5635)
val BerryOnTertiary = Color(0xFFFFFFFF)
val BerryTertiaryContainer = Color(0xFFFFDCC2)
val BerryOnTertiaryContainer = Color(0xFF2D1600)
val BerryBackground = Color(0xFFFFFBFF)
val BerryOnBackground = Color(0xFF201A1C)
val BerrySurface = Color(0xFFFFFBFF)
val BerryOnSurface = Color(0xFF201A1C)
val BerrySurfaceVariant = Color(0xFFF2DDE1)
val BerryOnSurfaceVariant = Color(0xFF514347)
val BerryError = Color(0xFFBA1A1A)
val BerryOnError = Color(0xFFFFFFFF)
val BerryErrorContainer = Color(0xFFFFDAD6)
val BerryOnErrorContainer = Color(0xFF410002)
val BerryOutline = Color(0xFF837377)

val BerryPrimaryDark = Color(0xFFFFB1C8)
val BerryOnPrimaryDark = Color(0xFF5E1133)
val BerryPrimaryContainerDark = Color(0xFF7B294A)
val BerryOnPrimaryContainerDark = Color(0xFFFFD9E2)
val BerrySecondaryDark = Color(0xFFE2BDC6)
val BerryOnSecondaryDark = Color(0xFF423940)
val BerrySecondaryContainerDark = Color(0xFF5A4F57)
val BerryOnSecondaryContainerDark = Color(0xFFFFD9E2)
val BerryTertiaryDark = Color(0xFFEFBD94)
val BerryOnTertiaryDark = Color(0xFF46290C)
val BerryTertiaryContainerDark = Color(0xFF5F3F20)
val BerryOnTertiaryContainerDark = Color(0xFFFFDCC2)
val BerryBackgroundDark = Color(0xFF201A1C)
val BerryOnBackgroundDark = Color(0xFFEDE0E3)
val BerrySurfaceDark = Color(0xFF201A1C)
val BerryOnSurfaceDark = Color(0xFFEDE0E3)
val BerrySurfaceVariantDark = Color(0xFF514347)
val BerryOnSurfaceVariantDark = Color(0xFFD3C2C6)
val BerryErrorDark = Color(0xFFFFB4AB)
val BerryOnErrorDark = Color(0xFF690005)
val BerryErrorContainerDark = Color(0xFF93000A)
val BerryOnErrorContainerDark = Color(0xFFFFDAD6)
val BerryOutlineDark = Color(0xFF9E8C90)

// ═══════════════════════════════════════════════════════
// 7. Forest Dark — тёмный лес
// ═══════════════════════════════════════════════════════
val ForestPrimary = Color(0xFF388E3C)
val ForestOnPrimary = Color(0xFFFFFFFF)
val ForestPrimaryContainer = Color(0xFFC8E6C9)
val ForestOnPrimaryContainer = Color(0xFF002204)
val ForestSecondary = Color(0xFF546E50)
val ForestOnSecondary = Color(0xFFFFFFFF)
val ForestSecondaryContainer = Color(0xFFD7E8D2)
val ForestOnSecondaryContainer = Color(0xFF121F10)
val ForestTertiary = Color(0xFF38656A)
val ForestOnTertiary = Color(0xFFFFFFFF)
val ForestTertiaryContainer = Color(0xFFBCEBEE)
val ForestOnTertiaryContainer = Color(0xFF002023)
val ForestBackground = Color(0xFFF8FAF4)
val ForestOnBackground = Color(0xFF1A1C18)
val ForestSurface = Color(0xFFF8FAF4)
val ForestOnSurface = Color(0xFF1A1C18)
val ForestSurfaceVariant = Color(0xFFDDE5D6)
val ForestOnSurfaceVariant = Color(0xFF414940)
val ForestError = Color(0xFFBA1A1A)
val ForestOnError = Color(0xFFFFFFFF)
val ForestErrorContainer = Color(0xFFFFDAD6)
val ForestOnErrorContainer = Color(0xFF410002)
val ForestOutline = Color(0xFF717970)

val ForestPrimaryDark = Color(0xFFA3D5A7)
val ForestOnPrimaryDark = Color(0xFF07390D)
val ForestPrimaryContainerDark = Color(0xFF1E5122)
val ForestOnPrimaryContainerDark = Color(0xFFC8E6C9)
val ForestSecondaryDark = Color(0xFFBBCBB5)
val ForestOnSecondaryDark = Color(0xFF263422)
val ForestSecondaryContainerDark = Color(0xFF3C4B38)
val ForestOnSecondaryContainerDark = Color(0xFFD7E8D2)
val ForestTertiaryDark = Color(0xFFA0CFD3)
val ForestOnTertiaryDark = Color(0xFF02363B)
val ForestTertiaryContainerDark = Color(0xFF1E4D51)
val ForestOnTertiaryContainerDark = Color(0xFFBCEBEE)
val ForestBackgroundDark = Color(0xFF1A1C18)
val ForestOnBackgroundDark = Color(0xFFE2E3DD)
val ForestSurfaceDark = Color(0xFF1A1C18)
val ForestOnSurfaceDark = Color(0xFFE2E3DD)
val ForestSurfaceVariantDark = Color(0xFF414940)
val ForestOnSurfaceVariantDark = Color(0xFFC1C9BE)
val ForestErrorDark = Color(0xFFFFB4AB)
val ForestOnErrorDark = Color(0xFF690005)
val ForestErrorContainerDark = Color(0xFF93000A)
val ForestOnErrorContainerDark = Color(0xFFFFDAD6)
val ForestOutlineDark = Color(0xFF8B9388)

// ═══════════════════════════════════════════════════════
// 8. Sand Earth — тёплые землистые тона
// ═══════════════════════════════════════════════════════
val SandPrimary = Color(0xFF8D6E63)
val SandOnPrimary = Color(0xFFFFFFFF)
val SandPrimaryContainer = Color(0xFFFFDBCF)
val SandOnPrimaryContainer = Color(0xFF3A0C04)
val SandSecondary = Color(0xFF775650)
val SandOnSecondary = Color(0xFFFFFFFF)
val SandSecondaryContainer = Color(0xFFFFDBCF)
val SandOnSecondaryContainer = Color(0xFF2C1511)
val SandTertiary = Color(0xFF705C2E)
val SandOnTertiary = Color(0xFFFFFFFF)
val SandTertiaryContainer = Color(0xFFFCDFA6)
val SandOnTertiaryContainer = Color(0xFF261A00)
val SandBackground = Color(0xFFFFFBFF)
val SandOnBackground = Color(0xFF201A18)
val SandSurface = Color(0xFFFFFBFF)
val SandOnSurface = Color(0xFF201A18)
val SandSurfaceVariant = Color(0xFFF5DDD7)
val SandOnSurfaceVariant = Color(0xFF534340)
val SandError = Color(0xFFBA1A1A)
val SandOnError = Color(0xFFFFFFFF)
val SandErrorContainer = Color(0xFFFFDAD6)
val SandOnErrorContainer = Color(0xFF410002)
val SandOutline = Color(0xFF857370)

val SandPrimaryDark = Color(0xFFFFB4A7)
val SandOnPrimaryDark = Color(0xFF5F1600)
val SandPrimaryContainerDark = Color(0xFF7D3E29)
val SandOnPrimaryContainerDark = Color(0xFFFFDBCF)
val SandSecondaryDark = Color(0xFFE7BDB5)
val SandOnSecondaryDark = Color(0xFF442924)
val SandSecondaryContainerDark = Color(0xFF5D3F3A)
val SandOnSecondaryContainerDark = Color(0xFFFFDBCF)
val SandTertiaryDark = Color(0xFFDFC38C)
val SandOnTertiaryDark = Color(0xFF3E2E04)
val SandTertiaryContainerDark = Color(0xFF574419)
val SandOnTertiaryContainerDark = Color(0xFFFCDFA6)
val SandBackgroundDark = Color(0xFF201A18)
val SandOnBackgroundDark = Color(0xFFEDE0DC)
val SandSurfaceDark = Color(0xFF201A18)
val SandOnSurfaceDark = Color(0xFFEDE0DC)
val SandSurfaceVariantDark = Color(0xFF534340)
val SandOnSurfaceVariantDark = Color(0xFFD8C2BE)
val SandErrorDark = Color(0xFFFFB4AB)
val SandOnErrorDark = Color(0xFF690005)
val SandErrorContainerDark = Color(0xFF93000A)
val SandOnErrorContainerDark = Color(0xFFFFDAD6)
val SandOutlineDark = Color(0xFFA08C89)

// ═══════════════════════════════════════════════════════
// 9. Midnight Navy — глубокий тёмно-синий
// ═══════════════════════════════════════════════════════
val NavyPrimary = Color(0xFF3F51B5)
val NavyOnPrimary = Color(0xFFFFFFFF)
val NavyPrimaryContainer = Color(0xFFDBE1FF)
val NavyOnPrimaryContainer = Color(0xFF00105C)
val NavySecondary = Color(0xFF585E71)
val NavyOnSecondary = Color(0xFFFFFFFF)
val NavySecondaryContainer = Color(0xFFDCE2F9)
val NavyOnSecondaryContainer = Color(0xFF151B2C)
val NavyTertiary = Color(0xFF735471)
val NavyOnTertiary = Color(0xFFFFFFFF)
val NavyTertiaryContainer = Color(0xFFFFD7F5)
val NavyOnTertiaryContainer = Color(0xFF2B122B)
val NavyBackground = Color(0xFFFBF8FF)
val NavyOnBackground = Color(0xFF1B1B1F)
val NavySurface = Color(0xFFFBF8FF)
val NavyOnSurface = Color(0xFF1B1B1F)
val NavySurfaceVariant = Color(0xFFE3E1EC)
val NavyOnSurfaceVariant = Color(0xFF46464F)
val NavyError = Color(0xFFBA1A1A)
val NavyOnError = Color(0xFFFFFFFF)
val NavyErrorContainer = Color(0xFFFFDAD6)
val NavyOnErrorContainer = Color(0xFF410002)
val NavyOutline = Color(0xFF777680)

val NavyPrimaryDark = Color(0xFFB6C4FF)
val NavyOnPrimaryDark = Color(0xFF002093)
val NavyPrimaryContainerDark = Color(0xFF1F35A8)
val NavyOnPrimaryContainerDark = Color(0xFFDBE1FF)
val NavySecondaryDark = Color(0xFFC0C6DD)
val NavyOnSecondaryDark = Color(0xFF2A3042)
val NavySecondaryContainerDark = Color(0xFF414659)
val NavyOnSecondaryContainerDark = Color(0xFFDCE2F9)
val NavyTertiaryDark = Color(0xFFE2BBDD)
val NavyOnTertiaryDark = Color(0xFF432742)
val NavyTertiaryContainerDark = Color(0xFF5B3D58)
val NavyOnTertiaryContainerDark = Color(0xFFFFD7F5)
val NavyBackgroundDark = Color(0xFF1B1B1F)
val NavyOnBackgroundDark = Color(0xFFE4E1E9)
val NavySurfaceDark = Color(0xFF1B1B1F)
val NavyOnSurfaceDark = Color(0xFFE4E1E9)
val NavySurfaceVariantDark = Color(0xFF46464F)
val NavyOnSurfaceVariantDark = Color(0xFFC7C5D0)
val NavyErrorDark = Color(0xFFFFB4AB)
val NavyOnErrorDark = Color(0xFF690005)
val NavyErrorContainerDark = Color(0xFF93000A)
val NavyOnErrorContainerDark = Color(0xFFFFDAD6)
val NavyOutlineDark = Color(0xFF91909A)

// ═══════════════════════════════════════════════════════
// 10. Coral Health — коралловый (health/fitness vibe)
// ═══════════════════════════════════════════════════════
val CoralPrimary = Color(0xFFFF6D3A)
val CoralOnPrimary = Color(0xFFFFFFFF)
val CoralPrimaryContainer = Color(0xFFFFDBD0)
val CoralOnPrimaryContainer = Color(0xFF3B0900)
val CoralSecondary = Color(0xFF77564D)
val CoralOnSecondary = Color(0xFFFFFFFF)
val CoralSecondaryContainer = Color(0xFFFFDBD0)
val CoralOnSecondaryContainer = Color(0xFF2C1511)
val CoralTertiary = Color(0xFF6D5D2F)
val CoralOnTertiary = Color(0xFFFFFFFF)
val CoralTertiaryContainer = Color(0xFFF7E1A7)
val CoralOnTertiaryContainer = Color(0xFF241B00)
val CoralBackground = Color(0xFFFFFBFF)
val CoralOnBackground = Color(0xFF201A17)
val CoralSurface = Color(0xFFFFFBFF)
val CoralOnSurface = Color(0xFF201A17)
val CoralSurfaceVariant = Color(0xFFF5DDD4)
val CoralOnSurfaceVariant = Color(0xFF53433E)
val CoralError = Color(0xFFBA1A1A)
val CoralOnError = Color(0xFFFFFFFF)
val CoralErrorContainer = Color(0xFFFFDAD6)
val CoralOnErrorContainer = Color(0xFF410002)
val CoralOutline = Color(0xFF85736D)

val CoralPrimaryDark = Color(0xFFFFB599)
val CoralOnPrimaryDark = Color(0xFF5F1800)
val CoralPrimaryContainerDark = Color(0xFF842B10)
val CoralOnPrimaryContainerDark = Color(0xFFFFDBD0)
val CoralSecondaryDark = Color(0xFFE7BDB3)
val CoralOnSecondaryDark = Color(0xFF442923)
val CoralSecondaryContainerDark = Color(0xFF5D3F37)
val CoralOnSecondaryContainerDark = Color(0xFFFFDBD0)
val CoralTertiaryDark = Color(0xFFD9C58D)
val CoralOnTertiaryDark = Color(0xFF3E3009)
val CoralTertiaryContainerDark = Color(0xFF55461D)
val CoralOnTertiaryContainerDark = Color(0xFFF7E1A7)
val CoralBackgroundDark = Color(0xFF201A17)
val CoralOnBackgroundDark = Color(0xFFEDE0DB)
val CoralSurfaceDark = Color(0xFF201A17)
val CoralOnSurfaceDark = Color(0xFFEDE0DB)
val CoralSurfaceVariantDark = Color(0xFF53433E)
val CoralOnSurfaceVariantDark = Color(0xFFD8C2BA)
val CoralErrorDark = Color(0xFFFFB4AB)
val CoralOnErrorDark = Color(0xFF690005)
val CoralErrorContainerDark = Color(0xFF93000A)
val CoralOnErrorContainerDark = Color(0xFFFFDAD6)
val CoralOutlineDark = Color(0xFFA08D86)

// Standard / Fallback
val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)
val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
