package com.abdulin.nutritionapp.ui.theme

import androidx.compose.ui.graphics.Color

// ═══════════════════════════════════════════════════════
// 1. Демо — яркая тема для проектора (чисто белый фон)
// ═══════════════════════════════════════════════════════
val DemoPrimary = Color(0xFF1565C0)
val DemoOnPrimary = Color(0xFFFFFFFF)
val DemoPrimaryContainer = Color(0xFFD1E4FF)
val DemoOnPrimaryContainer = Color(0xFF001D36)
val DemoSecondary = Color(0xFF535F70)
val DemoOnSecondary = Color(0xFFFFFFFF)
val DemoSecondaryContainer = Color(0xFFD7E3F7)
val DemoOnSecondaryContainer = Color(0xFF101C2B)
val DemoTertiary = Color(0xFF6B5778)
val DemoOnTertiary = Color(0xFFFFFFFF)
val DemoTertiaryContainer = Color(0xFFF2DAFF)
val DemoOnTertiaryContainer = Color(0xFF251431)
val DemoBackground = Color(0xFFFFFFFF)
val DemoOnBackground = Color(0xFF1B1B1F)
val DemoSurface = Color(0xFFFFFFFF)
val DemoOnSurface = Color(0xFF1B1B1F)
val DemoSurfaceVariant = Color(0xFFE8EAF0)
val DemoOnSurfaceVariant = Color(0xFF43474E)
val DemoError = Color(0xFFBA1A1A)
val DemoOnError = Color(0xFFFFFFFF)
val DemoErrorContainer = Color(0xFFFFDAD6)
val DemoOnErrorContainer = Color(0xFF410002)
val DemoOutline = Color(0xFF73777F)

val DemoPrimaryDark = Color(0xFFA0CAFD)
val DemoOnPrimaryDark = Color(0xFF003258)
val DemoPrimaryContainerDark = Color(0xFF00497D)
val DemoOnPrimaryContainerDark = Color(0xFFD1E4FF)
val DemoSecondaryDark = Color(0xFFBBC7DB)
val DemoOnSecondaryDark = Color(0xFF253140)
val DemoSecondaryContainerDark = Color(0xFF3B4858)
val DemoOnSecondaryContainerDark = Color(0xFFD7E3F7)
val DemoTertiaryDark = Color(0xFFD6BEE4)
val DemoOnTertiaryDark = Color(0xFF3B2948)
val DemoTertiaryContainerDark = Color(0xFF523F5F)
val DemoOnTertiaryContainerDark = Color(0xFFF2DAFF)
val DemoBackgroundDark = Color(0xFF1B1B1F)
val DemoOnBackgroundDark = Color(0xFFE3E2E6)
val DemoSurfaceDark = Color(0xFF1B1B1F)
val DemoOnSurfaceDark = Color(0xFFE3E2E6)
val DemoSurfaceVariantDark = Color(0xFF43474E)
val DemoOnSurfaceVariantDark = Color(0xFFC3C7CF)
val DemoErrorDark = Color(0xFFFFB4AB)
val DemoOnErrorDark = Color(0xFF690005)
val DemoErrorContainerDark = Color(0xFF93000A)
val DemoOnErrorContainerDark = Color(0xFFFFDAD6)
val DemoOutlineDark = Color(0xFF8D9199)

// ═══════════════════════════════════════════════════════
// 2. Классика — чистый нейтральный (Material baseline)
// ═══════════════════════════════════════════════════════
val ClassicPrimary = Color(0xFF6750A4)
val ClassicOnPrimary = Color(0xFFFFFFFF)
val ClassicPrimaryContainer = Color(0xFFE9DDFF)
val ClassicOnPrimaryContainer = Color(0xFF21005D)
val ClassicSecondary = Color(0xFF625B71)
val ClassicOnSecondary = Color(0xFFFFFFFF)
val ClassicSecondaryContainer = Color(0xFFE8DEF8)
val ClassicOnSecondaryContainer = Color(0xFF1D192B)
val ClassicTertiary = Color(0xFF7D5260)
val ClassicOnTertiary = Color(0xFFFFFFFF)
val ClassicTertiaryContainer = Color(0xFFFFD8E4)
val ClassicOnTertiaryContainer = Color(0xFF31111D)
val ClassicBackground = Color(0xFFFFFBFE)
val ClassicOnBackground = Color(0xFF1C1B1F)
val ClassicSurface = Color(0xFFFFFBFE)
val ClassicOnSurface = Color(0xFF1C1B1F)
val ClassicSurfaceVariant = Color(0xFFE7E0EC)
val ClassicOnSurfaceVariant = Color(0xFF49454E)
val ClassicError = Color(0xFFB3261E)
val ClassicOnError = Color(0xFFFFFFFF)
val ClassicErrorContainer = Color(0xFFF9DEDC)
val ClassicOnErrorContainer = Color(0xFF410E0B)
val ClassicOutline = Color(0xFF79747E)

val ClassicPrimaryDark = Color(0xFFD0BCFF)
val ClassicOnPrimaryDark = Color(0xFF381E72)
val ClassicPrimaryContainerDark = Color(0xFF4F378B)
val ClassicOnPrimaryContainerDark = Color(0xFFE9DDFF)
val ClassicSecondaryDark = Color(0xFFCCC2DC)
val ClassicOnSecondaryDark = Color(0xFF332D41)
val ClassicSecondaryContainerDark = Color(0xFF4A4458)
val ClassicOnSecondaryContainerDark = Color(0xFFE8DEF8)
val ClassicTertiaryDark = Color(0xFFEFB8C8)
val ClassicOnTertiaryDark = Color(0xFF4A2532)
val ClassicTertiaryContainerDark = Color(0xFF633B48)
val ClassicOnTertiaryContainerDark = Color(0xFFFFD8E4)
val ClassicBackgroundDark = Color(0xFF1C1B1F)
val ClassicOnBackgroundDark = Color(0xFFE6E1E5)
val ClassicSurfaceDark = Color(0xFF1C1B1F)
val ClassicOnSurfaceDark = Color(0xFFE6E1E5)
val ClassicSurfaceVariantDark = Color(0xFF49454E)
val ClassicOnSurfaceVariantDark = Color(0xFFCAC4D0)
val ClassicErrorDark = Color(0xFFF2B8B5)
val ClassicOnErrorDark = Color(0xFF601410)
val ClassicErrorContainerDark = Color(0xFF8C1D18)
val ClassicOnErrorContainerDark = Color(0xFFF9DEDC)
val ClassicOutlineDark = Color(0xFF938F99)

// ═══════════════════════════════════════════════════════
// 3. Океан — мягкий синий, спокойный
// ═══════════════════════════════════════════════════════
val OceanPrimary = Color(0xFF3A608F)
val OceanOnPrimary = Color(0xFFFFFFFF)
val OceanPrimaryContainer = Color(0xFFD6E3FF)
val OceanOnPrimaryContainer = Color(0xFF001C3A)
val OceanSecondary = Color(0xFF545F70)
val OceanOnSecondary = Color(0xFFFFFFFF)
val OceanSecondaryContainer = Color(0xFFD8E3F8)
val OceanOnSecondaryContainer = Color(0xFF111C2B)
val OceanTertiary = Color(0xFF6D5677)
val OceanOnTertiary = Color(0xFFFFFFFF)
val OceanTertiaryContainer = Color(0xFFF6D9FF)
val OceanOnTertiaryContainer = Color(0xFF271330)
val OceanBackground = Color(0xFFF9F9FF)
val OceanOnBackground = Color(0xFF191C20)
val OceanSurface = Color(0xFFF9F9FF)
val OceanOnSurface = Color(0xFF191C20)
val OceanSurfaceVariant = Color(0xFFDFE2EB)
val OceanOnSurfaceVariant = Color(0xFF43474E)
val OceanError = Color(0xFFBA1A1A)
val OceanOnError = Color(0xFFFFFFFF)
val OceanErrorContainer = Color(0xFFFFDAD6)
val OceanOnErrorContainer = Color(0xFF410002)
val OceanOutline = Color(0xFF73777F)

val OceanPrimaryDark = Color(0xFFAAC7FF)
val OceanOnPrimaryDark = Color(0xFF00305C)
val OceanPrimaryContainerDark = Color(0xFF194873)
val OceanOnPrimaryContainerDark = Color(0xFFD6E3FF)
val OceanSecondaryDark = Color(0xFFBCC7DB)
val OceanOnSecondaryDark = Color(0xFF263141)
val OceanSecondaryContainerDark = Color(0xFF3C4758)
val OceanOnSecondaryContainerDark = Color(0xFFD8E3F8)
val OceanTertiaryDark = Color(0xFFD9BDE3)
val OceanOnTertiaryDark = Color(0xFF3D2846)
val OceanTertiaryContainerDark = Color(0xFF543E5D)
val OceanOnTertiaryContainerDark = Color(0xFFF6D9FF)
val OceanBackgroundDark = Color(0xFF111318)
val OceanOnBackgroundDark = Color(0xFFE1E2E8)
val OceanSurfaceDark = Color(0xFF111318)
val OceanOnSurfaceDark = Color(0xFFE1E2E8)
val OceanSurfaceVariantDark = Color(0xFF43474E)
val OceanOnSurfaceVariantDark = Color(0xFFC3C7CF)
val OceanErrorDark = Color(0xFFFFB4AB)
val OceanOnErrorDark = Color(0xFF690005)
val OceanErrorContainerDark = Color(0xFF93000A)
val OceanOnErrorContainerDark = Color(0xFFFFDAD6)
val OceanOutlineDark = Color(0xFF8D9199)

// ═══════════════════════════════════════════════════════
// 4. Лес — мягкий зелёный, природный
// ═══════════════════════════════════════════════════════
val ForestPrimary = Color(0xFF4E6352)
val ForestOnPrimary = Color(0xFFFFFFFF)
val ForestPrimaryContainer = Color(0xFFD0E8D2)
val ForestOnPrimaryContainer = Color(0xFF0C1F12)
val ForestSecondary = Color(0xFF55624C)
val ForestOnSecondary = Color(0xFFFFFFFF)
val ForestSecondaryContainer = Color(0xFFD8E7CB)
val ForestOnSecondaryContainer = Color(0xFF131F0D)
val ForestTertiary = Color(0xFF386666)
val ForestOnTertiary = Color(0xFFFFFFFF)
val ForestTertiaryContainer = Color(0xFFBBECEC)
val ForestOnTertiaryContainer = Color(0xFF002020)
val ForestBackground = Color(0xFFF9FBF5)
val ForestOnBackground = Color(0xFF1A1C18)
val ForestSurface = Color(0xFFF9FBF5)
val ForestOnSurface = Color(0xFF1A1C18)
val ForestSurfaceVariant = Color(0xFFDDE5D6)
val ForestOnSurfaceVariant = Color(0xFF424940)
val ForestError = Color(0xFFBA1A1A)
val ForestOnError = Color(0xFFFFFFFF)
val ForestErrorContainer = Color(0xFFFFDAD6)
val ForestOnErrorContainer = Color(0xFF410002)
val ForestOutline = Color(0xFF727970)

val ForestPrimaryDark = Color(0xFFB5CCB7)
val ForestOnPrimaryDark = Color(0xFF213528)
val ForestPrimaryContainerDark = Color(0xFF374B3B)
val ForestOnPrimaryContainerDark = Color(0xFFD0E8D2)
val ForestSecondaryDark = Color(0xFFBDCBB1)
val ForestOnSecondaryDark = Color(0xFF283420)
val ForestSecondaryContainerDark = Color(0xFF3E4A36)
val ForestOnSecondaryContainerDark = Color(0xFFD8E7CB)
val ForestTertiaryDark = Color(0xFFA0D0D0)
val ForestOnTertiaryDark = Color(0xFF003737)
val ForestTertiaryContainerDark = Color(0xFF1E4E4E)
val ForestOnTertiaryContainerDark = Color(0xFFBBECEC)
val ForestBackgroundDark = Color(0xFF1A1C18)
val ForestOnBackgroundDark = Color(0xFFE2E3DD)
val ForestSurfaceDark = Color(0xFF1A1C18)
val ForestOnSurfaceDark = Color(0xFFE2E3DD)
val ForestSurfaceVariantDark = Color(0xFF424940)
val ForestOnSurfaceVariantDark = Color(0xFFC2C9BE)
val ForestErrorDark = Color(0xFFFFB4AB)
val ForestOnErrorDark = Color(0xFF690005)
val ForestErrorContainerDark = Color(0xFF93000A)
val ForestOnErrorContainerDark = Color(0xFFFFDAD6)
val ForestOutlineDark = Color(0xFF8C9388)

// ═══════════════════════════════════════════════════════
// 5. Закат — тёплый янтарный, уютный
// ═══════════════════════════════════════════════════════
val SunsetPrimary = Color(0xFF7D5800)
val SunsetOnPrimary = Color(0xFFFFFFFF)
val SunsetPrimaryContainer = Color(0xFFFFDEA6)
val SunsetOnPrimaryContainer = Color(0xFF281900)
val SunsetSecondary = Color(0xFF6D5D3F)
val SunsetOnSecondary = Color(0xFFFFFFFF)
val SunsetSecondaryContainer = Color(0xFFF6E0BB)
val SunsetOnSecondaryContainer = Color(0xFF261A04)
val SunsetTertiary = Color(0xFF4D6545)
val SunsetOnTertiary = Color(0xFFFFFFFF)
val SunsetTertiaryContainer = Color(0xFFD0EBC1)
val SunsetOnTertiaryContainer = Color(0xFF0B2006)
val SunsetBackground = Color(0xFFFFFBFF)
val SunsetOnBackground = Color(0xFF1E1B16)
val SunsetSurface = Color(0xFFFFFBFF)
val SunsetOnSurface = Color(0xFF1E1B16)
val SunsetSurfaceVariant = Color(0xFFEDE1CF)
val SunsetOnSurfaceVariant = Color(0xFF4D4639)
val SunsetError = Color(0xFFBA1A1A)
val SunsetOnError = Color(0xFFFFFFFF)
val SunsetErrorContainer = Color(0xFFFFDAD6)
val SunsetOnErrorContainer = Color(0xFF410002)
val SunsetOutline = Color(0xFF7F7667)

val SunsetPrimaryDark = Color(0xFFF1BF48)
val SunsetOnPrimaryDark = Color(0xFF412D00)
val SunsetPrimaryContainerDark = Color(0xFF5F4200)
val SunsetOnPrimaryContainerDark = Color(0xFFFFDEA6)
val SunsetSecondaryDark = Color(0xFFF0C48D)
val SunsetOnSecondaryDark = Color(0xFF3E2E14)
val SunsetSecondaryContainerDark = Color(0xFF55452A)
val SunsetOnSecondaryContainerDark = Color(0xFFF6E0BB)
val SunsetTertiaryDark = Color(0xFFB4D0A8)
val SunsetOnTertiaryDark = Color(0xFF20361B)
val SunsetTertiaryContainerDark = Color(0xFF364C30)
val SunsetOnTertiaryContainerDark = Color(0xFFD0EBC1)
val SunsetBackgroundDark = Color(0xFF1E1B16)
val SunsetOnBackgroundDark = Color(0xFFE9E2D7)
val SunsetSurfaceDark = Color(0xFF1E1B16)
val SunsetOnSurfaceDark = Color(0xFFE9E2D7)
val SunsetSurfaceVariantDark = Color(0xFF4D4639)
val SunsetOnSurfaceVariantDark = Color(0xFFD0C5B4)
val SunsetErrorDark = Color(0xFFFFB4AB)
val SunsetOnErrorDark = Color(0xFF690005)
val SunsetErrorContainerDark = Color(0xFF93000A)
val SunsetOnErrorContainerDark = Color(0xFFFFDAD6)
val SunsetOutlineDark = Color(0xFF9A9084)

// ═══════════════════════════════════════════════════════
// 6. Лаванда — мягкий фиолетовый, элегантный
// ═══════════════════════════════════════════════════════
val LavenderPrimary = Color(0xFF6750A4)
val LavenderOnPrimary = Color(0xFFFFFFFF)
val LavenderPrimaryContainer = Color(0xFFE9DDFF)
val LavenderOnPrimaryContainer = Color(0xFF21005D)
val LavenderSecondary = Color(0xFF625B71)
val LavenderOnSecondary = Color(0xFFFFFFFF)
val LavenderSecondaryContainer = Color(0xFFE8DEF8)
val LavenderOnSecondaryContainer = Color(0xFF1D192B)
val LavenderTertiary = Color(0xFF7D5260)
val LavenderOnTertiary = Color(0xFFFFFFFF)
val LavenderTertiaryContainer = Color(0xFFFFD8E4)
val LavenderOnTertiaryContainer = Color(0xFF31111D)
val LavenderBackground = Color(0xFFFFFBFE)
val LavenderOnBackground = Color(0xFF1C1B1F)
val LavenderSurface = Color(0xFFFFFBFE)
val LavenderOnSurface = Color(0xFF1C1B1F)
val LavenderSurfaceVariant = Color(0xFFE7E0EC)
val LavenderOnSurfaceVariant = Color(0xFF49454E)
val LavenderError = Color(0xFFB3261E)
val LavenderOnError = Color(0xFFFFFFFF)
val LavenderErrorContainer = Color(0xFFF9DEDC)
val LavenderOnErrorContainer = Color(0xFF410E0B)
val LavenderOutline = Color(0xFF79747E)

val LavenderPrimaryDark = Color(0xFFD0BCFF)
val LavenderOnPrimaryDark = Color(0xFF381E72)
val LavenderPrimaryContainerDark = Color(0xFF4F378B)
val LavenderOnPrimaryContainerDark = Color(0xFFE9DDFF)
val LavenderSecondaryDark = Color(0xFFCCC2DC)
val LavenderOnSecondaryDark = Color(0xFF332D41)
val LavenderSecondaryContainerDark = Color(0xFF4A4458)
val LavenderOnSecondaryContainerDark = Color(0xFFE8DEF8)
val LavenderTertiaryDark = Color(0xFFEFB8C8)
val LavenderOnTertiaryDark = Color(0xFF4A2532)
val LavenderTertiaryContainerDark = Color(0xFF633B48)
val LavenderOnTertiaryContainerDark = Color(0xFFFFD8E4)
val LavenderBackgroundDark = Color(0xFF1C1B1F)
val LavenderOnBackgroundDark = Color(0xFFE6E1E5)
val LavenderSurfaceDark = Color(0xFF1C1B1F)
val LavenderOnSurfaceDark = Color(0xFFE6E1E5)
val LavenderSurfaceVariantDark = Color(0xFF49454E)
val LavenderOnSurfaceVariantDark = Color(0xFFCAC4D0)
val LavenderErrorDark = Color(0xFFF2B8B5)
val LavenderOnErrorDark = Color(0xFF601410)
val LavenderErrorContainerDark = Color(0xFF8C1D18)
val LavenderOnErrorContainerDark = Color(0xFFF9DEDC)
val LavenderOutlineDark = Color(0xFF938F99)

// ═══════════════════════════════════════════════════════
// 7. Коралл — тёплый, живой
// ═══════════════════════════════════════════════════════
val CoralPrimary = Color(0xFF904A42)
val CoralOnPrimary = Color(0xFFFFFFFF)
val CoralPrimaryContainer = Color(0xFFFFDAD4)
val CoralOnPrimaryContainer = Color(0xFF3B0907)
val CoralSecondary = Color(0xFF775653)
val CoralOnSecondary = Color(0xFFFFFFFF)
val CoralSecondaryContainer = Color(0xFFFFDAD4)
val CoralOnSecondaryContainer = Color(0xFF2C1513)
val CoralTertiary = Color(0xFF725B2E)
val CoralOnTertiary = Color(0xFFFFFFFF)
val CoralTertiaryContainer = Color(0xFFFFDEA6)
val CoralOnTertiaryContainer = Color(0xFF271900)
val CoralBackground = Color(0xFFFFFBFF)
val CoralOnBackground = Color(0xFF201A19)
val CoralSurface = Color(0xFFFFFBFF)
val CoralOnSurface = Color(0xFF201A19)
val CoralSurfaceVariant = Color(0xFFF5DDDA)
val CoralOnSurfaceVariant = Color(0xFF534341)
val CoralError = Color(0xFFBA1A1A)
val CoralOnError = Color(0xFFFFFFFF)
val CoralErrorContainer = Color(0xFFFFDAD6)
val CoralOnErrorContainer = Color(0xFF410002)
val CoralOutline = Color(0xFF857370)

val CoralPrimaryDark = Color(0xFFFFB4A8)
val CoralOnPrimaryDark = Color(0xFF5F1511)
val CoralPrimaryContainerDark = Color(0xFF7D302A)
val CoralOnPrimaryContainerDark = Color(0xFFFFDAD4)
val CoralSecondaryDark = Color(0xFFE7BDB8)
val CoralOnSecondaryDark = Color(0xFF442927)
val CoralSecondaryContainerDark = Color(0xFF5D3F3D)
val CoralOnSecondaryContainerDark = Color(0xFFFFDAD4)
val CoralTertiaryDark = Color(0xFFE1C28C)
val CoralOnTertiaryDark = Color(0xFF402D04)
val CoralTertiaryContainerDark = Color(0xFF594319)
val CoralOnTertiaryContainerDark = Color(0xFFFFDEA6)
val CoralBackgroundDark = Color(0xFF201A19)
val CoralOnBackgroundDark = Color(0xFFEDE0DE)
val CoralSurfaceDark = Color(0xFF201A19)
val CoralOnSurfaceDark = Color(0xFFEDE0DE)
val CoralSurfaceVariantDark = Color(0xFF534341)
val CoralOnSurfaceVariantDark = Color(0xFFD8C2BF)
val CoralErrorDark = Color(0xFFFFB4AB)
val CoralOnErrorDark = Color(0xFF690005)
val CoralErrorContainerDark = Color(0xFF93000A)
val CoralOnErrorContainerDark = Color(0xFFFFDAD6)
val CoralOutlineDark = Color(0xFFA08C89)

// ═══════════════════════════════════════════════════════
// 8. Серый — нейтральный, минималистичный
// ═══════════════════════════════════════════════════════
val SlatePrimary = Color(0xFF5A5D62)
val SlateOnPrimary = Color(0xFFFFFFFF)
val SlatePrimaryContainer = Color(0xFFDDE3EA)
val SlateOnPrimaryContainer = Color(0xFF171C22)
val SlateSecondary = Color(0xFF53575E)
val SlateOnSecondary = Color(0xFFFFFFFF)
val SlateSecondaryContainer = Color(0xFFD7DBE2)
val SlateOnSecondaryContainer = Color(0xFF101318)
val SlateTertiary = Color(0xFF565E71)
val SlateOnTertiary = Color(0xFFFFFFFF)
val SlateTertiaryContainer = Color(0xFFDAE2F9)
val SlateOnTertiaryContainer = Color(0xFF131C2C)
val SlateBackground = Color(0xFFF9F9FC)
val SlateOnBackground = Color(0xFF1A1C1F)
val SlateSurface = Color(0xFFF9F9FC)
val SlateOnSurface = Color(0xFF1A1C1F)
val SlateSurfaceVariant = Color(0xFFDDE3EA)
val SlateOnSurfaceVariant = Color(0xFF41474D)
val SlateError = Color(0xFFBA1A1A)
val SlateOnError = Color(0xFFFFFFFF)
val SlateErrorContainer = Color(0xFFFFDAD6)
val SlateOnErrorContainer = Color(0xFF410002)
val SlateOutline = Color(0xFF71777D)

val SlatePrimaryDark = Color(0xFFC2C7CE)
val SlateOnPrimaryDark = Color(0xFF2C3137)
val SlatePrimaryContainerDark = Color(0xFF43454B)
val SlateOnPrimaryContainerDark = Color(0xFFDDE3EA)
val SlateSecondaryDark = Color(0xFFBBC1C9)
val SlateOnSecondaryDark = Color(0xFF252A31)
val SlateSecondaryContainerDark = Color(0xFF3B3F46)
val SlateOnSecondaryContainerDark = Color(0xFFD7DBE2)
val SlateTertiaryDark = Color(0xFFBEC6DC)
val SlateOnTertiaryDark = Color(0xFF283041)
val SlateTertiaryContainerDark = Color(0xFF3E4759)
val SlateOnTertiaryContainerDark = Color(0xFFDAE2F9)
val SlateBackgroundDark = Color(0xFF1A1C1F)
val SlateOnBackgroundDark = Color(0xFFE2E2E6)
val SlateSurfaceDark = Color(0xFF1A1C1F)
val SlateOnSurfaceDark = Color(0xFFE2E2E6)
val SlateSurfaceVariantDark = Color(0xFF41474D)
val SlateOnSurfaceVariantDark = Color(0xFFC1C7CE)
val SlateErrorDark = Color(0xFFFFB4AB)
val SlateOnErrorDark = Color(0xFF690005)
val SlateErrorContainerDark = Color(0xFF93000A)
val SlateOnErrorContainerDark = Color(0xFFFFDAD6)
val SlateOutlineDark = Color(0xFF8B9198)

// ═══════════════════════════════════════════════════════
// 9. Ягодный — мягкий розовый, тёплый
// ═══════════════════════════════════════════════════════
val BerryPrimary = Color(0xFF8D4E62)
val BerryOnPrimary = Color(0xFFFFFFFF)
val BerryPrimaryContainer = Color(0xFFFFD9E2)
val BerryOnPrimaryContainer = Color(0xFF3B0A1D)
val BerrySecondary = Color(0xFF74565F)
val BerryOnSecondary = Color(0xFFFFFFFF)
val BerrySecondaryContainer = Color(0xFFFFD9E2)
val BerryOnSecondaryContainer = Color(0xFF2B151C)
val BerryTertiary = Color(0xFF7C5635)
val BerryOnTertiary = Color(0xFFFFFFFF)
val BerryTertiaryContainer = Color(0xFFFFDCC2)
val BerryOnTertiaryContainer = Color(0xFF2D1600)
val BerryBackground = Color(0xFFFFFBFF)
val BerryOnBackground = Color(0xFF201A1C)
val BerrySurface = Color(0xFFFFFBFF)
val BerryOnSurface = Color(0xFF201A1C)
val BerrySurfaceVariant = Color(0xFFF2DDE1)
val BerryOnSurfaceVariant = Color(0xFF514347)
val BerryError = Color(0xFFBA1A1A)
val BerryOnError = Color(0xFFFFFFFF)
val BerryErrorContainer = Color(0xFFFFDAD6)
val BerryOnErrorContainer = Color(0xFF410002)
val BerryOutline = Color(0xFF837377)

val BerryPrimaryDark = Color(0xFFF8B1C5)
val BerryOnPrimaryDark = Color(0xFF572035)
val BerryPrimaryContainerDark = Color(0xFF72374C)
val BerryOnPrimaryContainerDark = Color(0xFFFFD9E2)
val BerrySecondaryDark = Color(0xFFE2BDC6)
val BerryOnSecondaryDark = Color(0xFF423940)
val BerrySecondaryContainerDark = Color(0xFF5A4F57)
val BerryOnSecondaryContainerDark = Color(0xFFFFD9E2)
val BerryTertiaryDark = Color(0xFFEFBD94)
val BerryOnTertiaryDark = Color(0xFF46290C)
val BerryTertiaryContainerDark = Color(0xFF5F3F20)
val BerryOnTertiaryContainerDark = Color(0xFFFFDCC2)
val BerryBackgroundDark = Color(0xFF201A1C)
val BerryOnBackgroundDark = Color(0xFFEDE0E3)
val BerrySurfaceDark = Color(0xFF201A1C)
val BerryOnSurfaceDark = Color(0xFFEDE0E3)
val BerrySurfaceVariantDark = Color(0xFF514347)
val BerryOnSurfaceVariantDark = Color(0xFFD3C2C6)
val BerryErrorDark = Color(0xFFFFB4AB)
val BerryOnErrorDark = Color(0xFF690005)
val BerryErrorContainerDark = Color(0xFF93000A)
val BerryOnErrorContainerDark = Color(0xFFFFDAD6)
val BerryOutlineDark = Color(0xFF9E8C90)

// ═══════════════════════════════════════════════════════
// 10. AMOLED — чистый чёрный
// ═══════════════════════════════════════════════════════
val AmoledPrimary = Color(0xFFD0BCFF)
val AmoledOnPrimary = Color(0xFF381E72)
val AmoledPrimaryContainer = Color(0xFF4F378B)
val AmoledOnPrimaryContainer = Color(0xFFE9DDFF)
val AmoledSecondary = Color(0xFFCCC2DC)
val AmoledOnSecondary = Color(0xFF332D41)
val AmoledSecondaryContainer = Color(0xFF4A4458)
val AmoledOnSecondaryContainer = Color(0xFFE8DEF8)
val AmoledTertiary = Color(0xFFEFB8C8)
val AmoledOnTertiary = Color(0xFF4A2532)
val AmoledTertiaryContainer = Color(0xFF633B48)
val AmoledOnTertiaryContainer = Color(0xFFFFD8E4)
val AmoledBackground = Color(0xFF000000)
val AmoledOnBackground = Color(0xFFE6E1E5)
val AmoledSurface = Color(0xFF000000)
val AmoledOnSurface = Color(0xFFE6E1E5)
val AmoledSurfaceVariant = Color(0xFF49454E)
val AmoledOnSurfaceVariant = Color(0xFFCAC4D0)
val AmoledError = Color(0xFFF2B8B5)
val AmoledOnError = Color(0xFF601410)
val AmoledErrorContainer = Color(0xFF8C1D18)
val AmoledOnErrorContainer = Color(0xFFF9DEDC)
val AmoledOutline = Color(0xFF938F99)
